SearchBar component pushed
pocketxtra/pocketxtra-ui-library pull request #10
Opened 2023-08-18 14:35 UTC by ShubhamBade

This branch has search bar component code. Thank you!!

2023-08-21 06:30 UTC, rohan-arya-w requested changes
Remove all Hardcoded values for colors

2023-08-21 06:30 UTC, rohan-arya-w commented on src/components/searchBar/SearchBar.tsx
> +    outlineColor = "#3D3E41",
Don't use Hardcoded color value

2023-08-21 06:31 UTC, rohan-arya-w requested changes

2023-08-21 06:31 UTC, rohan-arya-w commented on src/components/searchBar/index.ts
> +// export all types of buttons here
Remove the comment write something meaning full here

2023-08-22 13:35 UTC, tabassum2507 approved these changes

2023-08-22 13:35 UTC, tabassum2507 commented on src/components/searchBar/SearchBar.tsx
> +    errorMessage = '* Error: Payment Source is required',
Do we need error message in Search bar?

2023-08-22 13:59 UTC, rohan-arya-w approved these changes

2023-08-22 14:00 UTC, emailpocketxtra approved these changes

2023-08-22 14:47 UTC, merged