Pocketxtra 27 component cards
pocketxtra/pocketxtra-ui-library pull request #17
Opened 2023-08-21 09:05 UTC by tabassum2507

@rohan-arya-w blur effect is added in the background

2023-08-21 14:54 UTC, rohan-arya-w requested changes
format all files

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/CardComponentTemp.tsx
> +  EventLocation = "Delhi",
We don't need hardcoded values here

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/DashBoardInfoCard.tsx
> +
Remove extra Line

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/index.ts
> +export {DashBaordInfoCard} from './DashBoardInfoCard'
Semi colon missing

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  width = 50,
remove width size

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +          EventStatus === "UpComming" ? (
add all the const in const file

2023-08-21 14:54 UTC, rohan-arya-w commented on src/index.ts
> +import './components/cards/index' // import all buttons component here to the entry point for the npm package
Please add the correct comment

2023-08-21 14:54 UTC, rohan-arya-w commented on src/interface/cards/DashBoardInfoCardInterface.ts
> +    fontFamily?: string,
Do we need this ??

2023-08-21 14:54 UTC, rohan-arya-w commented on src/interface/cards/TempInterface.ts
> +    fontFamily?: string,
Remove font family from here

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  colorDark = '',
give something meaning full name

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  colorDark = '',
like textColor

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  fontFamily = 'Nunito'
Remove

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +
Remove extra line

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +            <BlurView style={[styles.cardContent, { borderBottomLeftRadius : responsiveWidth(3),
Remove inline styles

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +             <Text style={{ color: color, fontFamily: fontFamily, fontSize: responsiveFontSize(DesTextSize) }}>{Eventdes}</Text>
Remove inline styles

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +
remove extra line

2023-08-21 14:54 UTC, rohan-arya-w commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +
Remove extra space

2023-08-21 14:54 UTC, rohan-arya-w commented on src/interface/cards/TempInterface.ts
> +    Eventdes?: string,
Give proper naming

2023-08-22 04:45 UTC, tabassum2507 commented on src/components/cards/CardComponentTemp.tsx
> +  EventLocation = "Delhi",
hardcoded values are removed

2023-08-22 04:46 UTC, tabassum2507 commented on src/components/cards/DashBoardInfoCard.tsx
> +
Extra lines are removed from line no. 48 49

2023-08-22 04:47 UTC, tabassum2507 commented on src/components/cards/index.ts
> +export {DashBaordInfoCard} from './DashBoardInfoCard'
added

2023-08-22 04:49 UTC, tabassum2507 commented on src/index.ts
> +import './components/cards/index' // import all buttons component here to the entry point for the npm package
resolved

2023-08-22 04:52 UTC, tabassum2507 commented on src/interface/cards/TempInterface.ts
> +    fontFamily?: string,
resolved

2023-08-22 10:10 UTC, Amitrawat21 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
upcoming spelling mistake

2023-08-22 10:14 UTC, Amitrawat21 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
dashboard spelling mistake

2023-08-22 10:32 UTC, ShubhamBade commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  imageSource = { uri: 'https://picsum.photos/700' },
Create assets folder and store the reuired image. Then pass image path here. Dont not pass internet url. @rohan-arya-w  Please confirm

2023-08-22 10:35 UTC, tabassum2507 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
Resolved

2023-08-22 10:35 UTC, tabassum2507 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
resolved

2023-08-22 10:35 UTC, tabassum2507 commented on src/interface/cards/TempInterface.ts
> +    Eventdes?: string,
resolved

2023-08-22 10:36 UTC, tabassum2507 commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +
extra space removed

2023-08-22 10:36 UTC, tabassum2507 commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +
resolved

2023-08-22 10:37 UTC, ShubhamBade commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +        intensity={30}
@rohan-arya-w  do we need to change blur intensity to dynamic?

2023-08-22 10:37 UTC, tabassum2507 commented on src/components/cards/EditAndUpCommingEventCard.tsx
> +          EventStatus === "UpComming" ? (
resolved

2023-08-22 10:38 UTC, tabassum2507 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  width = 50,
width is 100% now

2023-08-22 10:40 UTC, tabassum2507 commented on src/interface/cards/DashBoardInfoCardInterface.ts
> +    fontFamily?: string,
font-family removed

2023-08-22 10:40 UTC, tabassum2507 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  colorDark = '',
name changed

2023-08-22 10:40 UTC, tabassum2507 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +
resolved

2023-08-22 10:45 UTC, ShubhamBade commented on src/components/cards/EditAndUpcomingEventCard.tsx
> +          borderRadius: responsiveWidth(3),
make it dynamic -borderRadius

2023-08-22 10:45 UTC, tabassum2507 commented on src/components/cards/DashBaordUpcommingEventCard.tsx
> +  fontFamily = 'Nunito'
font family removed

2023-08-22 13:04 UTC, tabassum2507 commented on src/components/cards/EditAndUpcomingEventCard.tsx
> +          borderRadius: responsiveWidth(3),
Resolved

2023-08-22 13:44 UTC, rohan-arya-w approved these changes

2023-08-22 14:02 UTC, emailpocketxtra approved these changes

2023-08-22 14:04 UTC, ShubhamBade approved these changes
done.

2023-08-22 14:14 UTC, merged