Button Components pushed
pocketxtra/pocketxtra-ui-library pull request #3
Opened 2023-08-17 14:06 UTC by rohan-arya-w

@rohan-arya-w  please review

2023-08-17 14:14 UTC, rohan-arya-w commented on src/components/buttons/PrimarySecondaryButton.tsx
Remove line no 24
Test

2023-08-21 02:53 UTC, emailpocketxtra submitted a review, later dismissed

2023-08-22 08:08 UTC, Amitrawat21 approved these changes, later dismissed

2023-08-22 13:56 UTC, emailpocketxtra approved these changes, later dismissed

2023-08-22 14:04 UTC, tabassum2507 approved these changes, later dismissed

2023-08-22 15:02 UTC, emailpocketxtra requested changes
22-AUG/08:30PM - Do not merge

2023-08-22 15:10 UTC, closed without merging