dropdown
pocketxtra/pocketxtra-ui-library pull request #4
Opened 2023-08-18 12:31 UTC by Amitrawat21

dropdown component

2023-08-21 02:55 UTC, emailpocketxtra reviewed
What is the purpose of 2 interfaces, DropDownInterface.ts / DropDownInterfaceTwo.ts??

2023-08-22 07:03 UTC, tabassum2507 requested changes

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/dropdown/DropDown.tsx
> +export const CustomDropDownComponent: React.FC<DropDownProps> = ({
change the interface name

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/dropdown/DropDown.tsx
> +  Coordinators,
what are coordinators?? give proper prop names

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/dropdown/DropDown.tsx
> +  iconsize
use camelcase

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/dropdown/DropDown.tsx
> +
remove extra lines

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/dropdown/DropDown.tsx
> +                flexDirection : "row",
use single or double quotes

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/dropdown/DropDown.tsx
> +                {coordinator.name}
remove coordinator and use other name

2023-08-22 07:03 UTC, tabassum2507 commented on src/components/footer/index.ts
> +import { DropDownProps } from '../../interface/DropDown/DropDownInterfaceTwo';
why are you making changes in footer?

2023-08-22 07:03 UTC, tabassum2507 commented on src/interface/DropDown/DropDownInterfaceTwo.ts
> + interface DropdownOption {
use camelcase

2023-08-22 13:56 UTC, rohan-arya-w approved these changes

2023-08-22 13:56 UTC, rohan-arya-w commented on src/components/dropdown/DropDown.tsx
> + export const DropDown: React.FC<DropDownProps> = ({
Changed the const name

2023-08-22 13:56 UTC, rohan-arya-w commented on src/components/dropdown/DropDown.tsx
> +    width = 65,
remove the hardcoded width

2023-08-22 13:56 UTC, rohan-arya-w commented on src/components/dropdown/DropDown.tsx
> +              color: '#808080',
remove the hardcoded color

2023-08-22 14:06 UTC, rohan-arya-w approved these changes

2023-08-22 14:21 UTC, tabassum2507 approved these changes

2023-08-22 14:42 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +                flexDirection : "row",
resolved

2023-08-22 14:45 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +
resolved

2023-08-22 14:45 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +              color: '#808080',
resolved

2023-08-22 14:46 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +    width = 65,
resolved

2023-08-22 14:46 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> + export const DropDown: React.FC<DropDownProps> = ({
resolved

2023-08-22 14:46 UTC, Amitrawat21 commented on src/interface/DropDown/DropDownInterfaceTwo.ts
> + interface DropdownOption {
resolved

2023-08-22 14:47 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +                {coordinator.name}
resolved

2023-08-22 14:48 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +  iconsize
resolved

2023-08-22 14:48 UTC, Amitrawat21 commented on src/components/dropdown/DropDown.tsx
> +export const CustomDropDownComponent: React.FC<DropDownProps> = ({
resolved

2023-08-22 15:01 UTC, merged