Image Upload Component created
pocketxtra/pocketxtra-ui-library pull request #9
Opened 2023-08-18 14:34 UTC by ShubhamBade

This branch has Image Upload component via Gallary and Camera. Please review it. Thank You!!

2023-08-21 06:14 UTC, ShubhamBade commented
camera icons color changed. Thank you!!

2023-08-21 06:28 UTC, rohan-arya-w requested changes

2023-08-21 06:28 UTC, rohan-arya-w commented on src/components/imagePicker/ImagePickerComp.tsx
> +    type = "gallary",
incorrect Spelling

2023-08-22 13:55 UTC, rohan-arya-w approved these changes

2023-08-22 13:57 UTC, emailpocketxtra approved these changes

2023-08-22 14:01 UTC, emailpocketxtra approved these changes

2023-08-22 14:05 UTC, tabassum2507 approved these changes

2023-08-22 14:05 UTC, tabassum2507 commented on src/components/imagePicker/ImagePickerComponent.tsx
> +    width = 40,
can we give 100 to the width?

2023-08-22 14:49 UTC, merged